name: chess_bot
description: chess bot

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.1.2+7

environment:
  sdk: ">=2.10.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: 0.17.0-nullsafety.2
  flutter_launcher_icons: ^0.8.1
  path_provider: ^1.6.24
  lite_rolling_switch: ^0.1.1
  shared_preferences: ^0.5.12+4
  group_radio_button: ^1.0.1
  quiver: ^2.1.5
  url_launcher: ^5.7.10
  #firebase
  firebase_core: ^0.5.3
  firebase_analytics: ^6.3.0
  cloud_firestore: ^0.14.4
  #internet connection checking
  connectivity: ^2.0.2
  data_connection_checker: ^0.3.4
  #json serialization
  json_annotation: ^3.1.1

  #for the chess board
  chess_vectors_flutter: ^1.0.12
  scoped_model: ^1.1.0

dev_dependencies:
  gen_lang: 0.1.3
  json_serializable: ^3.5.1
  build_runner: ^1.10.7

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  #the assets
  assets:
    - assets/
    - res/string/
    - res/drawable/
    - res/chess_board/
    - res/licenses/

#icons
flutter_icons:
  image_path_android: "res/drawable/ic_launcher.png"
  image_path_ios: "res/drawable/ic_launcher.png"
  android: true
  ios: true
